trigger:
- master
pool:
  vmImage: ubuntu-latest
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.7
- script: make install
  displayName: Install
- script: make ci
  displayName: CI
- task: Docker@2
  displayName: Build
  inputs:
    command: build
    repository: webtop
    tags: latest
